name = "allamo-pmo-cron"
main = "worker-cron.js"
compatibility_date = "2026-08-01"

[[d1_databases]]
binding = "DB"
database_name = "allamo-pmo"
database_id = "COLE_AQUI_O_ID_DO_D1"

[triggers]
crons = ["0 6 1 * *"]
